fix: hashtag alignment fix
freeCodeCamp/news pull request #478
Opened 2022-10-18 14:40 UTC by zairahira

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #198

The hashtags above post titles are not aligned properly as the hashtag is coming at the end.

2022-10-20 07:02 UTC, scissorsneedfoodtoo commented
Hey @zairahira, thanks for your patience.

I tested this locally, and unfortunately it doesn't seem to solve the issue we discussed in our last meeting.

All of the tags for the four views that show them (landing page cards, search results page cards, above post titles, tag page titles and popular tags) have the same issue, and show tags with the hashtag after the tag name and other text:

![image](https://user-images.githubusercontent.com/2051070/196875123-fef3f583-6d03-4300-95dd-f0d261733c43.png)

![image](https://user-images.githubusercontent.com/2051070/196875323-310481eb-7bb9-455e-99a3-e4bbcc81ec3f.png)

I believe it's because the CSS `direction` property really only works on block level elements, and inline elements like anchors need to have the `dir` attribute set directly.

The more robust fix would be to use the `dir` attribute in HTML elements as described in [this article](https://www.w3.org/International/questions/qa-html-dir).

But I think we can set some attributes directly now since tag names for RTL publications will always be in English like you, @Sboonny, and I talked about.

Here are some changes we can make in this PR rather than updating `screen.css`.

- `card.njk` (used for cards on the landing, tag, and author pages):

```
{% if primaryTag %}
    <span class="post-card-tags">
        <a dir="ltr" href="{{ primaryTag.path | url }}">
            #{{ primaryTag.name }}
        </a>
    </span>
{% endif %}
```

- `tag.njk`:

```
<h1 dir="ltr" data-test-label="tag-name" class="site-title tags-title">#{{ tag.name | upper }}</h1>
```

for the tag name heading, and

```
<a class='tag' href="{{ tag.path | url }}">
    <h3 dir="ltr">#{{ tag.name }} <small> | {{ tag.count.posts }}</small></h3>
</a>
```

for the list of popular tags.

- `post.njk` (the primary tag name above the post title):

```
<a dir="ltr" href="{{ primaryTag.path | url }}">
    #{{ primaryTag.name }}
</a>
```

- `search-results.js`:

```
${
  hit?.tags[0]?.name
    ? `<span class="post-card-tags"><a dir="ltr" href="${hit.tags[0].url}">
    #${hit.tags[0].name}
    </a></span>`
  : ''
}
```

All of these updates seem to fix tags in all the views that show them.

Would you like to make these updates and test them with a local build? Or would it be easier if I push some commits to your fork?

2022-10-20 08:27 UTC, zairahira commented
Kris, thank you for sharing the feedback. The changes for `screen.css` have been reverted for now.

I have tested the changes locally and they are looking good.

![image](https://user-images.githubusercontent.com/33151350/196897140-fd2c4779-c0c3-4c26-ad1e-9838b56d150e.png)



![image](https://user-images.githubusercontent.com/33151350/196896911-6e7138a6-1d3c-44d7-ac66-d8952215a742.png)

2022-10-21 03:09 UTC, scissorsneedfoodtoo requested changes
Hey @zairahira, thanks for making all of these updates and for those helpful screenshots.

I pulled your latest changes down and can confirm that the tag names are fixed in most places.

The one place it's still going the wrong direction is on the search results page:

![image](https://user-images.githubusercontent.com/2051070/197101622-2f764ab5-70d5-4790-8c60-9892300c0b7b.png)

The fix would be to set `dir` to `ltr` in the anchor on line 86 of `search-results.js`.

Here's what that section of code looks like:

```js
${
  hit?.tags[0]?.name
    ? `<span class="post-card-tags"><a dir="ltr" href="${hit.tags[0].url}">
    #${hit.tags[0].name}
    </a></span>`
  : ''
}
```

Could you go back in and do that when you get a chance?

2022-10-21 03:09 UTC, scissorsneedfoodtoo commented on src/search-results.njk
> +
Noticed an extra newline at the end of this file:

```suggestion
```

2022-10-21 07:26 UTC, zairahira commented
@scissorsneedfoodtoo my bad, I forgot to push those changes. I have done them now.

2022-10-21 08:42 UTC, scissorsneedfoodtoo approved these changes
Tested locally and everything LGTM 👍 

Thanks again for reporting this, @zairahira, and for all your help fixing these alignment issues.

2022-10-21 08:43 UTC, merged