fix: Standardize the height of the universal nav
freeCodeCamp/news pull request #754
Opened 2023-10-26 12:05 UTC by ahmaxed

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2023-10-26 12:07 UTC, ahmaxed commented on src/_includes/assets/css/screen.css
>    height: 40px;
```suggestion
```

2023-10-26 15:02 UTC, ShaunSHamilton reviewed
I am not sure the best way to review this (plugged the CSS into the dev-tool declarations). Seems good to me.

_Also wanted to say I spent a good few minutes wondering why this PR was not working on the forum_ 🤦‍♂️

2023-10-26 15:02 UTC, ShaunSHamilton commented on src/_includes/assets/css/screen.css
> +  margin-top: calc(var(--header-height) * 2 + 20px);
Why change this?

2023-10-26 15:08 UTC, ahmaxed commented
I think @scissorsneedfoodtoo would be the best person to review this.

2023-10-30 07:17 UTC, scissorsneedfoodtoo commented on src/_includes/assets/css/screen.css
> +  margin-top: calc(var(--header-height) * 2 + 20px);
My understanding is that this adds some spacing between the nav + donation banner and the rest of the page. Now that the header height has been increased, this formula needed to be adjusted so the spacing remains about the same.

2023-10-30 07:29 UTC, scissorsneedfoodtoo approved these changes
Everything LGTM.

I did a build of Japanese News and compared the height of the navbar to the one on Japanese Learn. With this updated styling, the height of the navbar matches the one on Learn on mobile, tablet, and desktop sized screens.

2023-10-30 07:38 UTC, scissorsneedfoodtoo requested changes
Sorry, spoke a bit too soon.

Looking at the author and tag pages, it seems like there's a bit of a gap between the donor banner and fCC blue background:

![image](https://github.com/freeCodeCamp/news/assets/2051070/c306a73d-d215-41b0-8598-32a303235ca8)

In `screen.css` on line 122, changing `margin-top` from `calc(var(--header-height) * 2)` to `calc(var(--header-height) * 1.7)` seems to do the trick.

Would you be able to add that to this PR, @ahmaxed?

2023-10-30 08:59 UTC, ahmaxed commented on src/_includes/assets/css/screen.css
> +  margin-top: calc(var(--header-height) * 2 + 20px);
```suggestion
  margin-top: calc(var(--header-height) * 1.7);
```

2023-10-30 09:00 UTC, ahmaxed commented
> In `screen.css` on line 122, changing `margin-top` from `calc(var(--header-height) * 2)` to `calc(var(--header-height) * 1.7)` seems to do the trick.
> 
> Would you be able to add that to this PR, @ahmaxed?

Thanks for taking a look. I added your suggestion to the margin-top.

2023-10-31 02:25 UTC, scissorsneedfoodtoo reviewed
Hey @ahmaxed, just checked this out and unfortunately the latest change doesn't give enough spacing between the navbar + donation banner in all views, and the date in posts just barely clears the donation banner now.

Sorry, I may not have been clear enough in my last comment.

I'd recommend going back to `margin-top: calc(var(--header-height) * 2 + 20px)` in the `.site-main` ruleset. That looked fine the way it was.

And I'm not able to select it and leave a suggestion, but on [line 122](https://github.com/freeCodeCamp/news/blob/e0eef89e0dc6e3cb301fedcab2d0715d5c599bd5/src/_includes/assets/css/screen.css#L122) within the `.under-header-content` ruleset, if you can change that to `margin-top: calc(var(--header-height) * 1.7)`, that should fix the spacing issue on tag and author pages.

2023-10-31 02:25 UTC, scissorsneedfoodtoo commented on src/_includes/assets/css/screen.css
> +  margin-top: calc(var(--header-height) * 1.7);
Going back to the original suggestion:

```suggestion
  margin-top: calc(var(--header-height) * 2 + 20px);
```

2023-10-31 06:40 UTC, ahmaxed commented
Sorry for the confusion. This should do it.

2023-11-03 07:31 UTC, scissorsneedfoodtoo approved these changes
Thanks for your patience, @ahmaxed, and for making that update.

Just checked locally and everything LGTM 👍

2023-11-03 07:36 UTC, merged