fix: remove groups from footer in english
freeCodeCamp/news pull request #782
Opened 2023-11-13 14:31 UTC by ahmaxed

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2023-11-13 16:01 UTC, sidemt requested changes

2023-11-13 16:01 UTC, sidemt commented on config/i18n/locales/french/translations.json
> +    "mission-statement": "Our mission: to help people learn to code for free. We accomplish this by creating thousands of videos, articles, and interactive coding lessons - all freely available to th
The files other than English will be updated through Crowdin. So we don't need to update it here.

2023-11-13 16:01 UTC, sidemt commented on config/i18n/locales/korean/translations.json
> +    "mission-statement": "Our mission: to help people learn to code for free. We accomplish this by creating thousands of videos, articles, and interactive coding lessons - all freely available to th
The files other than English will be updated through Crowdin. So we don't need to update it here.

2023-11-14 12:11 UTC, ahmaxed commented on config/i18n/locales/french/translations.json
> +    "mission-statement": "Our mission: to help people learn to code for free. We accomplish this by creating thousands of videos, articles, and interactive coding lessons - all freely available to th
```suggestion
    "mission-statement": "Our mission: to help people learn to code for free. We accomplish this by creating thousands of videos, articles, and interactive coding lessons - all freely available to the public. We also have thousands of freeCodeCamp study groups around the world.",
```

2023-11-14 12:11 UTC, ahmaxed commented on config/i18n/locales/korean/translations.json
> +    "mission-statement": "Our mission: to help people learn to code for free. We accomplish this by creating thousands of videos, articles, and interactive coding lessons - all freely available to th
```suggestion
    "mission-statement": "Our mission: to help people learn to code for free. We accomplish this by creating thousands of videos, articles, and interactive coding lessons - all freely available to the public. We also have thousands of freeCodeCamp study groups around the world.",
```

2023-11-14 14:24 UTC, sidemt approved these changes
LGTM

2023-11-14 14:25 UTC, merged