Revert "fix: Standardize the height of the universal nav"
freeCodeCamp/news pull request #790
Opened 2024-01-16 11:46 UTC by ahmaxed

There has been a change in the technical specifications.
Reverts freeCodeCamp/news#754

2024-01-16 16:14 UTC, naomi-lgbt requested changes

2024-01-16 16:14 UTC, naomi-lgbt commented on src/_includes/assets/css/screen.css
> +  height: 38px;
Which of these do we want? There are two `height` properties.

2024-01-23 15:53 UTC, ahmaxed commented on src/_includes/assets/css/screen.css
> +  height: 40px;
```suggestion
```

2024-01-23 15:53 UTC, ahmaxed commented on src/_includes/assets/css/screen.css
> +  height: 38px;
```suggestion
  height: var(--header-height);
```

2024-01-23 18:27 UTC, naomi-lgbt approved these changes

2024-01-23 18:27 UTC, merged